import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";
import { cx } from "@/styled-system/css";
import { flex } from "@/styled-system/patterns";
import { Providers } from "@/components/providers";

// Roobert PRO TRIAL
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Phi",
  description: "Generated by create-wagmi",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={cx(inter.className, flex({ direction: "column", align: "center", p: "1rem", bgColor: "bgWeak" }))}>
        <Providers>{props.children}</Providers>
      </body>
    </html>
  );
}
