# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "paris"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.23"
  src = "src"
  test = "test"
  build_info = true
  extra_output = ["storageLayout"]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  base = { key = "${API_KEY_BASE}" }
  base_sepolia = { key = "${API_KEY_BASE}" }
  

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  sepolia = "https://rpc.ankr.com/eth_sepolia"
  base = "${BASE_MAINNET_RPC}"
  base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_BASE_SEPOLIA}"

